# Venture Funding with Deep Learning

You work as a risk management associate at Alphabet Soup, a venture capital firm. Alphabet Soup’s business team receives many funding applications from startups every day. This team has asked you to help them create a model that predicts whether applicants will be successful if funded by Alphabet Soup.

The business team has given you a CSV containing more than 34,000 organizations that have received funding from Alphabet Soup over the years. With your knowledge of machine learning and neural networks, you decide to use the features in the provided dataset to create a binary classifier model that will predict whether an applicant will become a successful business. The CSV file contains a variety of information about these businesses, including whether or not they ultimately became successful.

## Instructions:

The steps for this challenge are broken out into the following sections:

* Prepare the data for use on a neural network model.

* Compile and evaluate a binary classification model using a neural network.

* Optimize the neural network model.

### Prepare the Data for Use on a Neural Network Model 

Using your knowledge of Pandas and scikit-learn’s `StandardScaler()`, preprocess the dataset so that you can use it to compile and evaluate the neural network model later.

Open the starter code file, and complete the following data preparation steps:

1. Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.   

2. Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.
 
3. Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

4. Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course. 

5. Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset. 

6. Split the features and target sets into training and testing datasets.

7. Use scikit-learn's `StandardScaler` to scale the features data.

### Compile and Evaluate a Binary Classification Model Using a Neural Network

Use your knowledge of TensorFlow to design a binary classification deep neural network model. This model should use the dataset’s features to predict whether an Alphabet Soup&ndash;funded startup will be successful based on the features in the dataset. Consider the number of inputs before determining the number of layers that your model will contain or the number of neurons on each layer. Then, compile and fit your model. Finally, evaluate your binary classification model to calculate the model’s loss and accuracy. 
 
To do so, complete the following steps:

1. Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

2. Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

> **Hint** When fitting the model, start with a small number of epochs, such as 20, 50, or 100.

3. Evaluate the model using the test data to determine the model’s loss and accuracy.

4. Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`. 

### Optimize the Neural Network Model

Using your knowledge of TensorFlow and Keras, optimize your model to improve the model's accuracy. Even if you do not successfully achieve a better accuracy, you'll need to demonstrate at least two attempts to optimize the model. You can include these attempts in your existing notebook. Or, you can make copies of the starter notebook in the same folder, rename them, and code each model optimization in a new notebook. 

> **Note** You will not lose points if your model does not achieve a high accuracy, as long as you make at least two attempts to optimize the model.

To do so, complete the following steps:

1. Define at least three new deep neural network models (the original plus 2 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

2. After finishing your models, display the accuracy scores achieved by each model, and compare the results.

3. Save each of your models as an HDF5 file.

In [134]:
# Imports
import pandas as pd
from pathlib import Path
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder

---

## Prepare the data to be used on a neural network model

### Step 1: Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.

In [135]:
# Read the applicants_data.csv file from the Resources folder into a Pandas DataFrame
applicant_data_df = pd.read_csv(
    "./Resources/applicants_data.csv",
)

# Review the DataFrame
applicant_data_df

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...,...,...
34294,996009318,THE LIONS CLUB OF HONOLULU KAMEHAMEHA,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,996010315,INTERNATIONAL ASSOCIATION OF LIONS CLUBS,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,996012607,PTA HAWAII CONGRESS,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,996015768,AMERICAN FEDERATION OF GOVERNMENT EMPLOYEES LO...,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,996086871,WATERHOUSE CHARITABLE TR,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [136]:
# Review the data types associated with the columns
applicant_data_df.dtypes

EIN                        int64
NAME                      object
APPLICATION_TYPE          object
AFFILIATION               object
CLASSIFICATION            object
USE_CASE                  object
ORGANIZATION              object
STATUS                     int64
INCOME_AMT                object
SPECIAL_CONSIDERATIONS    object
ASK_AMT                    int64
IS_SUCCESSFUL              int64
dtype: object

### Step 2: Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.

In [137]:
# Drop the 'EIN' and 'NAME' columns from the DataFrame
applicant_data_df = applicant_data_df.drop(
    columns=['EIN',
        'NAME']
)

# Review the DataFrame
applicant_data_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

### Step 3: Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

In [138]:
# Create a list of categorical variables 
categorical_variables = list(
    applicant_data_df.dtypes[applicant_data_df.dtypes == "object"].index
)

# Display the categorical variables list
categorical_variables

['APPLICATION_TYPE',
 'AFFILIATION',
 'CLASSIFICATION',
 'USE_CASE',
 'ORGANIZATION',
 'INCOME_AMT',
 'SPECIAL_CONSIDERATIONS']

In [139]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(
    sparse=False
)

In [140]:
# Encode the categorcal variables using OneHotEncoder
encoded_data = enc.fit_transform(
    applicant_data_df[categorical_variables]
)

In [141]:
# Create a DataFrame with the encoded variables
encoded_df = pd.DataFrame(
    encoded_data,
    columns= enc.get_feature_names_out(
        categorical_variables
    )
)

# Review the DataFrame
encoded_df

,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,APPLICATION_TYPE_T25,APPLICATION_TYPE_T29,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34295,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34296,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34297,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34298,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0

### Step 4: Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course.

In [142]:
# Create a variable to hold the numerical variables from the original dataframe
numerical_variables = applicant_data_df.drop(
    columns = categorical_variables
)

In [143]:
# Add the numerical variables from the original DataFrame to the one-hot encoding DataFrame
encoded_df = pd.concat(
    [encoded_df,
     numerical_variables],
    axis=1
)

# Review the Dataframe
encoded_df

,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,APPLICATION_TYPE_T25,APPLICATION_TYPE_T29,...,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y,STATUS,ASK_AMT,IS_SUCCESSFUL
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000,1
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,108590,1
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000,0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,6692,1
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,142590,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000,0
34295,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000,0
34296,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000,0
34297,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000,1
34298,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1,36500179,0

### Step 5: Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset.

In [144]:
# Define the target set y using the IS_SUCCESSFUL column
y = encoded_df['IS_SUCCESSFUL']

# Display a sample of y
y[:5]

0    1
1    1
2    0
3    1
4    1
Name: IS_SUCCESSFUL, dtype: int64

In [145]:
# Define features set X by selecting all columns but IS_SUCCESSFUL
X = encoded_df.drop(
    columns = ['IS_SUCCESSFUL']
)

# Review the features DataFrame
X.head()

,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,APPLICATION_TYPE_T25,APPLICATION_TYPE_T29,...,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y,STATUS,ASK_AMT
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,108590
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,6692
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,142590

### Step 6: Split the features and target sets into training and testing datasets.

In [146]:
# Split the preprocessed data into a training and testing dataset
# Assign the function a random_state equal to 1
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    random_state=1
)

### Step 7: Use scikit-learn's `StandardScaler` to scale the features data.

In [147]:
# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the scaler to the features training dataset
X_scaler = scaler.fit(X_train)

# Fit the scaler to the features training dataset
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

---

## Compile and Evaluate a Binary Classification Model Using a Neural Network

### Step 1: Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

In [148]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

116

In [149]:
# Define the number of neurons in the output layer
number_output_neurons = 1

In [150]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1 = (number_input_features + 1) // 2

# Review the number hidden nodes in the first layer
hidden_nodes_layer1

58

In [151]:
# Define the number of hidden nodes for the second hidden layer
hidden_nodes_layer2 = (hidden_nodes_layer1 + 1) // 2

# Review the number hidden nodes in the second layer
hidden_nodes_layer2

29

In [152]:
# Create the Sequential model instance
nn = Sequential()

In [153]:
# Add the first hidden layer
nn.add(
    Dense(
        units=hidden_nodes_layer1,
        input_dim=number_input_features,
        activation="relu")
)

In [154]:
# Add the second hidden layer
nn.add(
    Dense(
        units=hidden_nodes_layer2,
        activation="relu")
)

In [155]:
# Add the output layer to the model specifying the number of output neurons and activation function
nn.add(
    Dense(
        units= number_output_neurons,
        activation="sigmoid")
)

In [156]:
# Display the Sequential model summary
nn.summary()

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_32 (Dense)            (None, 58)                6786

 dense_33 (Dense)            (None, 29)                1711

 dense_34 (Dense)            (None, 1)                 30

=================================================================
Total params: 8,527
Trainable params: 8,527
Non-trainable params: 0
_________________________________________________________________

### Step 2: Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

In [157]:
# Compile the Sequential model
nn.compile(
    loss="binary_crossentropy", 
    optimizer="adam", 
    metrics=["accuracy"]
)

In [158]:
# Fit the model using 50 epochs and the training data
fit_model = nn.fit(
    X_train_scaled,
    y_train,
    epochs=50
)

Epoch 1/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5788 - accuracy: 0.7137
Epoch 2/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5533 - accuracy: 0.7285
Epoch 3/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5492 - accuracy: 0.7317
Epoch 4/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5470 - accuracy: 0.7323
Epoch 5/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5459 - accuracy: 0.7318
Epoch 6/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5448 - accuracy: 0.7330
Epoch 7/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5443 - accuracy: 0.7331
Epoch 8/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5427 - accuracy: 0.7345
Epoch 9/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5426 - accuracy: 0.7346
Epoch 10/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5420 - accuracy: 0.7352
Epoch 11/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5413 - accuracy: 0.7342
Epoch 12/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5407 - accuracy: 0.7364
Epoch 13/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5414 - accuracy: 0.7363
Epoch 14/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5403 - accuracy: 0.7378
Epoch 15/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5394 - accuracy: 0.7369
Epoch 16/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5389 - accuracy: 0.7367
Epoch 17/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5385 - accuracy: 0.7369
Epoch 18/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5383 - accuracy: 0.7369
Epoch 19/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5377 - accuracy: 0.7377
Epoch 20/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5378 - accuracy: 0.7387
Epoch 21/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5372 - accuracy: 0.7370
Epoch 22/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5369 - accuracy: 0.7383
Epoch 23/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5363 - accuracy: 0.7377
Epoch 24/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5362 - accuracy: 0.7380
Epoch 25/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5361 - accuracy: 0.7393
Epoch 26/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5358 - accuracy: 0.7391
Epoch 27/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5355 - accuracy: 0.7385
Epoch 28/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5357 - accuracy: 0.7376
Epoch 29/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5355 - accuracy: 0.7388
Epoch 30/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5350 - accuracy: 0.7405
Epoch 31/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5347 - accuracy: 0.7383
Epoch 32/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5347 - accuracy: 0.7396
Epoch 33/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5343 - accuracy: 0.7395
Epoch 34/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5340 - accuracy: 0.7395
Epoch 35/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5340 - accuracy: 0.7404
Epoch 36/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5336 - accuracy: 0.7398
Epoch 37/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5333 - accuracy: 0.7400
Epoch 38/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5336 - accuracy: 0.7408
Epoch 39/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5333 - accuracy: 0.7411
Epoch 40/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5337 - accuracy: 0.7398
Epoch 41/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5326 - accuracy: 0.7407
Epoch 42/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5331 - accuracy: 0.7401
Epoch 43/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5325 - accuracy: 0.7409
Epoch 44/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5325 - accuracy: 0.7404
Epoch 45/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5324 - accuracy: 0.7406
Epoch 46/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5323 - accuracy: 0.7411
Epoch 47/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5320 - accuracy: 0.7399
Epoch 48/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5320 - accuracy: 0.7405
Epoch 49/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5320 - accuracy: 0.7403
Epoch 50/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5318 - accuracy: 0.7412

### Step 3: Evaluate the model using the test data to determine the model’s loss and accuracy.

In [159]:
# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(
    X_test_scaled,
    y_test, 
    verbose=2
)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5552 - accuracy: 0.7277 - 540ms/epoch - 2ms/step
Loss: 0.5552008748054504, Accuracy: 0.7276967763900757

### Step 4: Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`.

In [160]:
# Set the model's file path
file_path = Path(
    "./Resources/AlphabetSoup.h5"
)

# Export your model to a HDF5 file
nn.save(file_path)

---

## Optimize the neural network model

### Step 1: Define at least three new deep neural network models (resulting in the original plus 3 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

### Alternative Model 1

In [161]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

116

In [162]:
# Define the number of neurons in the output layer
number_output_neurons_A1 = 1

In [163]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A1 = (number_input_features // 2) + 52

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A1

110

In [164]:
# Define the number of hidden nodes for the second hidden layer
hidden_nodes_layer2_A1 = (hidden_nodes_layer1_A1 // 2) + 37

# Review the number of hidden nodes in the second layer
hidden_nodes_layer2_A1

92

In [165]:
# Create the Sequential model instance
nn_A1 = Sequential()

In [166]:
# First hidden layer
nn_A1.add(
    Dense(
        units=hidden_nodes_layer1_A1,
        input_dim=number_input_features,
        activation="tanh")
)

# Second hidden layer
nn_A1.add(
    Dense(
        units=hidden_nodes_layer2_A1,
        activation="tanh")
)

# Output layer
nn_A1.add(
    Dense(
        units= number_output_neurons_A1,
        activation="sigmoid")
)

# Check the structure of the model
nn_A1.summary()

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_35 (Dense)            (None, 110)               12870

 dense_36 (Dense)            (None, 92)                10212

 dense_37 (Dense)            (None, 1)                 93

=================================================================
Total params: 23,175
Trainable params: 23,175
Non-trainable params: 0
_________________________________________________________________

In [167]:
# Compile the Sequential model
nn_A1.compile(
    loss="binary_crossentropy", 
    optimizer="adam", 
    metrics=["accuracy"]
)

In [168]:
# Fit the model using 80 epochs and the training data
fit_model_A1 = nn_A1.fit(
    X_train_scaled,
    y_train,
    epochs=80
)

Epoch 1/80
804/804 [==============================] - 3s 3ms/step - loss: 0.5762 - accuracy: 0.7187
Epoch 2/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5569 - accuracy: 0.7265
Epoch 3/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5516 - accuracy: 0.7292
Epoch 4/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5489 - accuracy: 0.7306
Epoch 5/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5466 - accuracy: 0.7323
Epoch 6/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5455 - accuracy: 0.7319
Epoch 7/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5438 - accuracy: 0.7356
Epoch 8/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5431 - accuracy: 0.7347
Epoch 9/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5420 - accuracy: 0.7351
Epoch 10/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5417 - accuracy: 0.7357
Epoch 11/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5402 - accuracy: 0.7366
Epoch 12/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5399 - accuracy: 0.7380
Epoch 13/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5387 - accuracy: 0.7356
Epoch 14/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5387 - accuracy: 0.7384
Epoch 15/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5375 - accuracy: 0.7369
Epoch 16/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5373 - accuracy: 0.7362
Epoch 17/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5367 - accuracy: 0.7380
Epoch 18/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5362 - accuracy: 0.7383
Epoch 19/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5353 - accuracy: 0.7391
Epoch 20/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5349 - accuracy: 0.7399
Epoch 21/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5347 - accuracy: 0.7383
Epoch 22/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5340 - accuracy: 0.7391
Epoch 23/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5334 - accuracy: 0.7397
Epoch 24/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5334 - accuracy: 0.7388
Epoch 25/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5332 - accuracy: 0.7397
Epoch 26/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5323 - accuracy: 0.7394
Epoch 27/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5326 - accuracy: 0.7406
Epoch 28/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5318 - accuracy: 0.7407
Epoch 29/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5315 - accuracy: 0.7402
Epoch 30/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5316 - accuracy: 0.7395
Epoch 31/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5313 - accuracy: 0.7418
Epoch 32/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5309 - accuracy: 0.7404
Epoch 33/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5305 - accuracy: 0.7418
Epoch 34/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5302 - accuracy: 0.7420
Epoch 35/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5300 - accuracy: 0.7420
Epoch 36/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5299 - accuracy: 0.7409
Epoch 37/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5297 - accuracy: 0.7420
Epoch 38/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5297 - accuracy: 0.7409
Epoch 39/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5293 - accuracy: 0.7410
Epoch 40/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5289 - accuracy: 0.7423
Epoch 41/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5289 - accuracy: 0.7413
Epoch 42/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5291 - accuracy: 0.7421
Epoch 43/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5283 - accuracy: 0.7416
Epoch 44/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5284 - accuracy: 0.7427
Epoch 45/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5286 - accuracy: 0.7421
Epoch 46/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5283 - accuracy: 0.7430
Epoch 47/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5278 - accuracy: 0.7420
Epoch 48/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5284 - accuracy: 0.7422
Epoch 49/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5277 - accuracy: 0.7422
Epoch 50/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5272 - accuracy: 0.7425
Epoch 51/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5266 - accuracy: 0.7427
Epoch 52/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5276 - accuracy: 0.7423
Epoch 53/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5272 - accuracy: 0.7433
Epoch 54/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5271 - accuracy: 0.7424
Epoch 55/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5273 - accuracy: 0.7414
Epoch 56/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5269 - accuracy: 0.7425
Epoch 57/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5267 - accuracy: 0.7429
Epoch 58/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5269 - accuracy: 0.7420
Epoch 59/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5265 - accuracy: 0.7429
Epoch 60/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5268 - accuracy: 0.7426
Epoch 61/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5262 - accuracy: 0.7431
Epoch 62/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5263 - accuracy: 0.7426
Epoch 63/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5262 - accuracy: 0.7422
Epoch 64/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5262 - accuracy: 0.7420
Epoch 65/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5259 - accuracy: 0.7439
Epoch 66/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5258 - accuracy: 0.7427
Epoch 67/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5257 - accuracy: 0.7435
Epoch 68/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5259 - accuracy: 0.7435
Epoch 69/80
804/804 [==============================] - 3s 3ms/step - loss: 0.5259 - accuracy: 0.7425
Epoch 70/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5259 - accuracy: 0.7421
Epoch 71/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5258 - accuracy: 0.7433
Epoch 72/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5258 - accuracy: 0.7429
Epoch 73/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5263 - accuracy: 0.7437
Epoch 74/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5251 - accuracy: 0.7434
Epoch 75/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5255 - accuracy: 0.7432
Epoch 76/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5253 - accuracy: 0.7427
Epoch 77/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5251 - accuracy: 0.7437
Epoch 78/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5253 - accuracy: 0.7433
Epoch 79/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5250 - accuracy: 0.7428
Epoch 80/80
804/804 [==============================] - 3s 3ms/step - loss: 0.5251 - accuracy: 0.7431

#### Alternative Model 2

In [169]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

116

In [170]:
# Define the number of neurons in the output layer
number_output_neurons_A2 = 1

In [171]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A2 = (number_input_features // 2) + 25

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A2

83

In [172]:
# Define the number of hidden nodes for the second hidden layer
hidden_nodes_layer2_A2 = (hidden_nodes_layer1_A2 // 2) + 25

# Review the number of hidden nodes in the second layer
hidden_nodes_layer2_A2

66

In [173]:
# Define the number of hidden nodes for the third hidden layer
hidden_nodes_layer3_A2 = (hidden_nodes_layer2_A2 // 2) + 25

# Review the number of hidden nodes in the third layer
hidden_nodes_layer3_A2

58

In [174]:
# Create the Sequential model instance
nn_A2 = Sequential()

In [175]:
# First hidden layer
nn_A2.add(
    Dense(
        units=hidden_nodes_layer1_A2,
        input_dim=number_input_features,
        activation="tanh")
)

# Second hidden layer
nn_A2.add(
    Dense(
        units=hidden_nodes_layer2_A2,
        activation="tanh")
)

# Third hidden layer
nn_A2.add(
    Dense(
        units=hidden_nodes_layer3_A2,
        activation="tanh")
)

# Output layer
nn_A2.add(
    Dense(
        units= number_output_neurons_A2,
        activation="sigmoid")
)

# Check the structure of the model
nn_A2.summary()

Model: "sequential_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_38 (Dense)            (None, 83)                9711

 dense_39 (Dense)            (None, 66)                5544

 dense_40 (Dense)            (None, 58)                3886

 dense_41 (Dense)            (None, 1)                 59

=================================================================
Total params: 19,200
Trainable params: 19,200
Non-trainable params: 0
_________________________________________________________________

In [176]:
# Compile the model
nn_A2.compile(
    loss="binary_crossentropy", 
    optimizer="adam", 
    metrics=["accuracy"]
)

In [177]:
# Fit the model
fit_model_A2 = nn_A2.fit(
    X_train_scaled,
    y_train,
    epochs=80
)

Epoch 1/80
804/804 [==============================] - 4s 3ms/step - loss: 0.5700 - accuracy: 0.7203
Epoch 2/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5554 - accuracy: 0.7269
Epoch 3/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5520 - accuracy: 0.7299
Epoch 4/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5491 - accuracy: 0.7309
Epoch 5/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5470 - accuracy: 0.7332
Epoch 6/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5456 - accuracy: 0.7331
Epoch 7/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5432 - accuracy: 0.7345
Epoch 8/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5432 - accuracy: 0.7326
Epoch 9/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5418 - accuracy: 0.7355
Epoch 10/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5407 - accuracy: 0.7358
Epoch 11/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5402 - accuracy: 0.7366
Epoch 12/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5388 - accuracy: 0.7367
Epoch 13/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5385 - accuracy: 0.7370
Epoch 14/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5378 - accuracy: 0.7367
Epoch 15/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5369 - accuracy: 0.7376
Epoch 16/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5358 - accuracy: 0.7371
Epoch 17/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5357 - accuracy: 0.7387
Epoch 18/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5353 - accuracy: 0.7388
Epoch 19/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5346 - accuracy: 0.7384
Epoch 20/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5342 - accuracy: 0.7386
Epoch 21/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5337 - accuracy: 0.7393
Epoch 22/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5328 - accuracy: 0.7402
Epoch 23/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5328 - accuracy: 0.7400
Epoch 24/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5323 - accuracy: 0.7398
Epoch 25/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5317 - accuracy: 0.7410
Epoch 26/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5312 - accuracy: 0.7411
Epoch 27/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5313 - accuracy: 0.7405
Epoch 28/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5307 - accuracy: 0.7409
Epoch 29/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5308 - accuracy: 0.7403
Epoch 30/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5299 - accuracy: 0.7406
Epoch 31/80
804/804 [==============================] - 3s 4ms/step - loss: 0.5301 - accuracy: 0.7415
Epoch 32/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5298 - accuracy: 0.7407
Epoch 33/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5294 - accuracy: 0.7414
Epoch 34/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5294 - accuracy: 0.7425
Epoch 35/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5289 - accuracy: 0.7406
Epoch 36/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5288 - accuracy: 0.7420
Epoch 37/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5290 - accuracy: 0.7421
Epoch 38/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5284 - accuracy: 0.7420
Epoch 39/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5281 - accuracy: 0.7413
Epoch 40/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5279 - accuracy: 0.7423
Epoch 41/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5279 - accuracy: 0.7418
Epoch 42/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5277 - accuracy: 0.7425
Epoch 43/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5276 - accuracy: 0.7428
Epoch 44/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5277 - accuracy: 0.7418
Epoch 45/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5278 - accuracy: 0.7422
Epoch 46/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5270 - accuracy: 0.7427
Epoch 47/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5273 - accuracy: 0.7436
Epoch 48/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5270 - accuracy: 0.7430
Epoch 49/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5272 - accuracy: 0.7428
Epoch 50/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5271 - accuracy: 0.7435
Epoch 51/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5265 - accuracy: 0.7428
Epoch 52/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5263 - accuracy: 0.7433
Epoch 53/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5263 - accuracy: 0.7427
Epoch 54/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5265 - accuracy: 0.7434
Epoch 55/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5263 - accuracy: 0.7424
Epoch 56/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5265 - accuracy: 0.7428
Epoch 57/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5259 - accuracy: 0.7437
Epoch 58/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5260 - accuracy: 0.7432
Epoch 59/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5258 - accuracy: 0.7434
Epoch 60/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5257 - accuracy: 0.7446
Epoch 61/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5257 - accuracy: 0.7435
Epoch 62/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5254 - accuracy: 0.7434
Epoch 63/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5256 - accuracy: 0.7426
Epoch 64/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5255 - accuracy: 0.7433
Epoch 65/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5256 - accuracy: 0.7434
Epoch 66/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5251 - accuracy: 0.7430
Epoch 67/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5252 - accuracy: 0.7438
Epoch 68/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5256 - accuracy: 0.7430
Epoch 69/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5255 - accuracy: 0.7439
Epoch 70/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5250 - accuracy: 0.7432
Epoch 71/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5254 - accuracy: 0.7432
Epoch 72/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5252 - accuracy: 0.7428
Epoch 73/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5252 - accuracy: 0.7434
Epoch 74/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5251 - accuracy: 0.7446
Epoch 75/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5250 - accuracy: 0.7437
Epoch 76/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5251 - accuracy: 0.7426
Epoch 77/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5247 - accuracy: 0.7439
Epoch 78/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5247 - accuracy: 0.7439
Epoch 79/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5250 - accuracy: 0.7426
Epoch 80/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5246 - accuracy: 0.7440

### Step 2: After finishing your models, display the accuracy scores achieved by each model, and compare the results.

In [178]:
print("Original Model Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled, y_test, verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Original Model Results
268/268 - 0s - loss: 0.5552 - accuracy: 0.7277 - 449ms/epoch - 2ms/step
Loss: 0.5552008748054504, Accuracy: 0.7276967763900757

In [179]:
print("Alternative Model 1 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn_A1.evaluate(X_test_scaled, y_test, verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 1 Results
268/268 - 1s - loss: 0.5588 - accuracy: 0.7272 - 530ms/epoch - 2ms/step
Loss: 0.5587539076805115, Accuracy: 0.7272303104400635

In [180]:
print("Alternative Model 2 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn_A2.evaluate(X_test_scaled, y_test, verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 2 Results
268/268 - 1s - loss: 0.5593 - accuracy: 0.7291 - 536ms/epoch - 2ms/step
Loss: 0.5592836737632751, Accuracy: 0.7290962338447571

### Step 3: Save each of your alternative models as an HDF5 file.

In [181]:
# Set the file path for the first alternative model
file_path = Path(
    "./Resources/AlphabetSoup_Alternative_1.h5"
)

# Export your model to a HDF5 file
nn_A1.save(file_path)

In [182]:
# Set the file path for the second alternative model
file_path = Path(
    "./Resources/AlphabetSoup_Alternative_2.h5"
)

# Export your model to a HDF5 file
nn_A2.save(file_path)